version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'dldnjsdn'
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'wonwoo'
      MYSQL_PASSWORD: 'dldnjsdn'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS: -Xmx1024m -Xms1024m"