version: '2'
services:
  blog:
    image: wonwoo/blog
    container_name: blog
    depends_on:
      - mysql
      - elasticsearch
    ports:
     - 8080:8080
    entrypoint: ["./wait-for-it.sh","elasticsearch:9200","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  indexer:
    image: wonwoo/indexer
    container_name: indexer
    depends_on:
      - mysql
      - elasticsearch
    entrypoint: ["./wait-for-it.sh","blog:8080","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'dldnjsdn'
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'wonwoo'
      MYSQL_PASSWORD: 'dldnjsdn'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS: -Xmx1024m -Xms1024m"

